"""Storage abstraction.

Sources, triage and notification all talk to `Store` and never to SQLite
directly, so swapping in Airtable or Postgres later is a single new class rather
than a rewrite. `upsert` / `seen` / `recent` are the core three; the rest exist
because later phases genuinely need persistence across runs (notification rate
caps and the zero-yield alarm cannot work off in-memory state when every run is
a fresh GitHub Actions container).
"""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime
from typing import Any, Iterable, Protocol, runtime_checkable

from jobpipe.models import Disqualifier, Posting, Status, Tier


@dataclass(slots=True)
class UpsertResult:
    """Outcome of one `upsert` batch."""

    new: list[Posting] = field(default_factory=list)
    updated: list[Posting] = field(default_factory=list)
    # Rows collapsed onto an id already present *within this same batch* - i.e.
    # two sources reporting the same job in one run. Tracked separately from
    # `updated` because cross-source overlap is a metric EVAL.md reports on.
    collisions: int = 0
    # apply_url replaced because a higher-precedence source supplied a better one.
    url_upgrades: int = 0

    @property
    def new_count(self) -> int:
        return len(self.new)

    @property
    def deduped_out(self) -> int:
        return len(self.updated) + self.collisions


@runtime_checkable
class Store(Protocol):
    # --- core ---
    def upsert(self, postings: Iterable[Posting]) -> UpsertResult: ...
    def seen(self, id_or_key: str) -> bool: ...
    def recent(
        self,
        limit: int = 50,
        *,
        since: datetime | None = None,
        status: Status | None = None,
        tier: Tier | None = None,
    ) -> list[Posting]: ...

    # --- triage + lifecycle ---
    def get(self, posting_id: str) -> Posting | None: ...
    def update_triage(
        self,
        posting_id: str,
        *,
        tier: Tier,
        score: int,
        rationale: str,
        disqualifiers: list[Disqualifier],
        tier_source: str = "heuristic",
    ) -> None: ...
    def set_status(
        self, posting_id: str, status: Status, *, applied_at: datetime | None = None
    ) -> bool: ...
    def backlog_unapplied(self) -> int: ...

    # --- run bookkeeping ---
    def record_raw(self, run_id: str, source: str, payload: Any) -> None: ...
    def get_raw(self, run_id: str) -> list[tuple[str, Any]]: ...
    def record_run(self, report: dict[str, Any]) -> None: ...
    def prune_raw(self, keep_runs: int = 3) -> int: ...
    def vacuum(self) -> None: ...
    def runs(self, *, since: datetime | None = None) -> list[dict[str, Any]]: ...
    def record_notification(
        self, posting_id: str, tier: Tier, *, sent_at: datetime | None = None
    ) -> None: ...
    def notifications_since(self, since: datetime, *, tier: Tier | None = None) -> int: ...
    def last_new_posting_at(self) -> datetime | None: ...

    # --- baseline (cutover) ---
    def seed_baseline(self, ids: Iterable[str], *, seeded_at: datetime | None = None) -> int: ...
    def in_baseline(self, posting_id: str) -> bool: ...
    def baseline_ids(self) -> set[str]: ...
    def baseline_count(self) -> int: ...
    def promote_from_baseline(self, posting_id: str) -> None: ...
    def demote_to_baseline(self, posting_id: str) -> None: ...

    # --- suppressions (baseline) ---
    def record_suppressions(
        self, rows: Iterable[dict[str, Any]], *, now: datetime | None = None
    ) -> int: ...
    def recent_suppressions(self, limit: int = 50, *, since: datetime | None = None): ...
    def suppression_collapse(self, limit: int = 20) -> list[dict[str, Any]]: ...
    def suppression_count(self) -> int: ...
    def prune_suppressions(self, days: int = 30) -> int: ...

    # --- score cache (permanent; --replay must not re-bill) ---
    def cache_score(
        self, posting_id: str, score: int, rationale: str, tier_source: str,
        *, model: str | None = None,
    ) -> None: ...
    def get_cached_score(self, posting_id: str) -> dict[str, Any] | None: ...
    def score_cache_size(self) -> int: ...

    # --- exclusions ---
    def record_exclusions(self, rows: Iterable[dict[str, Any]], *, filter_version: str) -> int: ...
    def sample_exclusions(self, n: int = 20, *, reason: str | None = None) -> list[dict[str, Any]]: ...
    def exclusion_counts(self) -> dict[str, int]: ...
    def prune_exclusions(self, days: int = 14) -> int: ...

    # --- link quality ---
    def set_link_status(
        self, posting_id: str, status: str, final_url: str | None,
        *, checked_at: datetime | None = None,
    ) -> None: ...
    def link_status_counts(self) -> dict[str, dict[str, int]]: ...
    def needing_link_check(self, limit: int | None = None) -> list[Posting]: ...

    # --- sightings / expiry ---
    def mark_seen(self, ids: Iterable[str], run_id: str) -> None: ...
    def mark_missed(self, ids: Iterable[str], *, now: datetime | None = None) -> None: ...
    def expire_stale(self, *, absent_hours: int = 48, now: datetime | None = None) -> list[str]: ...
    def retire_long_expired(self, *, days: int = 90, now: datetime | None = None) -> list[str]: ...

    # --- conditional-request cache ---
    def get_cache_validators(self, url: str) -> tuple[str | None, str | None]: ...
    def set_cache_validators(
        self, url: str, etag: str | None, last_modified: str | None
    ) -> None: ...


from jobpipe.store.sqlite import SqliteStore  # noqa: E402

__all__ = ["Store", "SqliteStore", "UpsertResult"]
